// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flash_chat_app/secrets.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: firebaseWebAppId,
    messagingSenderId: firebaseWebMessagingSenderId,
    projectId: firebaseWebMessagingSenderId,
    authDomain: firebaseWebAuthDomain,
    storageBucket: firebaseWebStorageBucket,
    measurementId: firebaseWebMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApiKey,
    appId: firebaseAndroidAppId,
    messagingSenderId: firebaseAndroidMessagingSenderId,
    projectId: firebaseAndroidProjectId,
    storageBucket: firebaseAndroidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIosAppKey,
    appId: firebaseIosAppId,
    messagingSenderId: firebaseIosMessagingSenderId,
    projectId: firebaseIosProjectId,
    storageBucket: firebaseIosStorageBucket,
    iosClientId: firebaseIosClientId,
    iosBundleId: firebaseIosBundleId,
  );
}
