// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_l8XLeCgbvDiXr1lgK6HdAEiG8d0UdZI',
    appId: '1:378269185598:web:03c6e6e50398f48684036f',
    messagingSenderId: '378269185598',
    projectId: 'flutter-flash-chat-63a06',
    authDomain: 'flutter-flash-chat-63a06.firebaseapp.com',
    storageBucket: 'flutter-flash-chat-63a06.appspot.com',
    measurementId: 'G-TMFK3SV2Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7d9PlxjGfNglhVgWN69zwnIJUe1kuCHg',
    appId: '1:378269185598:android:c72fdec5bbc959f284036f',
    messagingSenderId: '378269185598',
    projectId: 'flutter-flash-chat-63a06',
    storageBucket: 'flutter-flash-chat-63a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzXPciLWDePsWWgTr0Dm-ew5Aw14mnzo',
    appId: '1:378269185598:ios:7dca16448f277f9c84036f',
    messagingSenderId: '378269185598',
    projectId: 'flutter-flash-chat-63a06',
    storageBucket: 'flutter-flash-chat-63a06.appspot.com',
    iosClientId: '378269185598-l0av1ff3duqhr82p0fi76bnbe528884m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChatApp',
  );
}
